source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'InfoCity' do
react_native_path = "../node_modules/react-native"
pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
pod "React", :path => react_native_path

pod 'GoogleMaps'
pod 'react-native-maps', path: '../'
pod 'react-native-google-maps', path: '../'
end

